import com.android.build.api.dsl.CommonExtension
import com.demo.buildlogic.KOTLIN_JVM_TARGET
import com.demo.buildlogic._libs
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.kotlin.dsl.apply
import org.gradle.kotlin.dsl.assign
import org.gradle.kotlin.dsl.configure
import org.gradle.kotlin.dsl.dependencies
import org.jetbrains.kotlin.gradle.dsl.KotlinAndroidProjectExtension
import org.jetbrains.kotlin.gradle.dsl.KotlinBaseExtension
import org.jetbrains.kotlin.gradle.dsl.KotlinJvmProjectExtension

interface BPDomainPlugin: Plugin<Project> {

    override fun apply(target: Project) {
        with(target) {
            val libs = _libs

            apply(plugin = libs.findPlugin("jetbrains.kotlin.jvm").get().get().pluginId)

            // KotlinJvmExtension was previously called KotlinJvmProjectExtension for pure kotlin modules
            // AGP includes kotlin, and they provide KotlinAndroidProjectExtension, I will use this extensions
            // for now, I may refactor this later, in that transition "kotlinOptions" was replaced with
            // "compilerOptions". This is the "kotlin" DSL
            extensions.configure<KotlinJvmProjectExtension> {
                // Treat all Kotlin warnings as errors (disabled by default)
                // Override by setting warningsAsErrors=true in your ~/.gradle/gradle.properties
                val warningsAsErrors = providers.gradleProperty("warningsAsErrors").map {
                    it.toBoolean()
                }.orElse(true)

                // jvmTarget.set(JvmTarget.JVM_21) // jvm target was (in the previous extension) set like this line
                // jvmToolchain(21) // this does the same as setting jvmTarget but also does a lot more
                compilerOptions {
                    // this sets generated bytecode compatibility
                    jvmTarget.set(KOTLIN_JVM_TARGET)
                    allWarningsAsErrors = true
                }
            }
        }
    }
}