package com.demo.buildlogic

import com.android.build.api.dsl.CommonExtension
import org.gradle.api.Project
import org.gradle.api.plugins.JavaPluginExtension
import org.gradle.kotlin.dsl.assign
import org.gradle.kotlin.dsl.configure
import org.jetbrains.kotlin.gradle.dsl.KotlinAndroidExtension
import org.jetbrains.kotlin.gradle.dsl.KotlinAndroidProjectExtension
import org.jetbrains.kotlin.gradle.dsl.KotlinBaseExtension
import org.jetbrains.kotlin.gradle.dsl.KotlinJvmProjectExtension

context(common: CommonExtension)
fun Project.configureAndroidKotlinAndJavaSourceCodeCompilation() {
    common.compileOptions.apply {
        sourceCompatibility = DEFAULT_SOURCE_COMPATIBILITY
        targetCompatibility = DEFAULT_TARGET_COMPATIBILITY
    }

    common.lint.apply {
        abortOnError = true
        warningsAsErrors = true

        checkGeneratedSources = true
        checkDependencies = false
    }

    configureKotlin<KotlinAndroidProjectExtension>()
}

fun Project.configureKotlinAndJavaSourceCodeCompilation() {
    extensions.configure<JavaPluginExtension> {
        sourceCompatibility = DEFAULT_SOURCE_COMPATIBILITY
        targetCompatibility = DEFAULT_TARGET_COMPATIBILITY
    }

    configureKotlin<KotlinJvmProjectExtension>()
}

private inline fun <reified T: KotlinBaseExtension> Project.configureKotlin() {
    if (this is KotlinJvmProjectExtension || this is KotlinAndroidExtension) {
        //  AGP now includes Kotlin, it provides KotlinAndroidProjectExtension in android app
        //  and libraries modules and KotlinJvmProjectExtension in pure Kotlin modules.
        //  "kotlinOptions" was replaced recently by "compilerOptions". Below configurations
        //  are the "kotlin" DSL
        configure<T> {
            // jvmTarget.set(JvmTarget.JVM_21) // jvm target was (in the previous extension) set like this line
            // jvmToolchain(21) // this does the same as setting jvmTarget but also does a lot more

            compilerOptions {
                // Treat all Kotlin warnings as errors (disabled by default)
                // Override by setting warningsAsErrors=true in your ~/.gradle/gradle.properties
                val warningsAsErrors = providers.gradleProperty("warningsAsErrors").map {
                    it.toBoolean()
                }.orElse(true)

                // this sets generated bytecode compatibility
                jvmTarget.set(KOTLIN_JVM_TARGET)
                allWarningsAsErrors = true
            }
        }
    } else {
        throw IllegalStateException("Kotlin Extension Implementation not supported")
    }
}