package com.demo.buildlogic

import com.android.build.api.dsl.CommonExtension
import org.gradle.kotlin.dsl.configure
import org.jetbrains.kotlin.gradle.dsl.KotlinAndroidProjectExtension

// this could have lived in separate functions, one for android and one for kotlin since they actually
// use different extensions(DSLs) but since they are kind of related I will centralize it here
fun CommonExtension.configureAndroidAndKotlinSourceCodeCompilation() {
    compileOptions.apply {
        sourceCompatibility = DEFAULT_SOURCE_COMPATIBILITY
        targetCompatibility = DEFAULT_TARGET_COMPATIBILITY
    }

    // KotlinJvmExtension was previously called KotlinJvmProjectExtension for pure kotlin modules
    // AGP includes kotlin, and they provide KotlinAndroidProjectExtension, I will use this extensions
    // for now, I may refactor this later, in that transition "kotlinOptions" was replaced with
    // "compilerOptions". This is the "kotlin" DSL
    extensions.configure<KotlinAndroidProjectExtension> {
        // jvmTarget.set(JvmTarget.JVM_21) // jvm target was previously(in the previous extension) set like this
        // jvmToolchain(21) // this does the same as setting jvmTarget but also does a lot more

        compilerOptions {
            // this sets generated bytecode compatibility
            jvmTarget.set(KOTLIN_JVM_TARGET)
        }
    }
}