package com.demo.buildlogic

import com.android.build.api.dsl.CommonExtension
import org.gradle.api.Project
import org.gradle.kotlin.dsl.assign
import org.gradle.kotlin.dsl.configure
import org.gradle.kotlin.dsl.support.kotlinCompilerOptions
import org.jetbrains.kotlin.gradle.dsl.KotlinAndroidProjectExtension
import org.jetbrains.kotlin.gradle.dsl.KotlinBaseExtension

// this could have lived in separate functions, one for android and one for kotlin since they actually
// use different extensions(DSLs) but since they are kind of related I will centralize it here
context(common: CommonExtension)
fun Project.configureKotlinAndAndroidSourceCodeCompilation() {
    common.compileOptions.apply {
        sourceCompatibility = DEFAULT_SOURCE_COMPATIBILITY
        targetCompatibility = DEFAULT_TARGET_COMPATIBILITY
    }

    common.lint.apply {
        abortOnError = true
        warningsAsErrors = true

        checkGeneratedSources = true
        checkDependencies = false
    }

    // KotlinJvmExtension was previously called KotlinJvmProjectExtension for pure kotlin modules
    // AGP includes kotlin, and they provide KotlinAndroidProjectExtension, I will use this extensions
    // for now, I may refactor this later, in that transition "kotlinOptions" was replaced with
    // "compilerOptions". This is the "kotlin" DSL
    extensions.configure<KotlinAndroidProjectExtension> {
        // Treat all Kotlin warnings as errors (disabled by default)
        // Override by setting warningsAsErrors=true in your ~/.gradle/gradle.properties
        val warningsAsErrors = providers.gradleProperty("warningsAsErrors").map {
            it.toBoolean()
        }.orElse(true)

        // jvmTarget.set(JvmTarget.JVM_21) // jvm target was (in the previous extension) set like this line
        // jvmToolchain(21) // this does the same as setting jvmTarget but also does a lot more
        compilerOptions {
            // this sets generated bytecode compatibility
            jvmTarget.set(KOTLIN_JVM_TARGET)
            allWarningsAsErrors = true
        }
    }
}